const API='/api';
const tokenKey='dx_token';
let state={page:'home',id:null,resetToken:null,cat:'All',products:[],cart:JSON.parse(localStorage.getItem('dx_cart')||'[]'),user:null,conversations:[],conversation:null,messages:[]};
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
async function api(path,opt={}){const headers={'Content-Type':'application/json',...(opt.headers||{})};const t=localStorage.getItem(tokenKey);if(t)headers.Authorization='Bearer '+t;const r=await fetch(API+path,{...opt,headers});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||'Request failed');return data}
function save(){localStorage.setItem('dx_cart',JSON.stringify(state.cart))}
function stars(n){n=Number(n||0);return '<span class="stars">'+('★'.repeat(Math.round(n)))+('☆'.repeat(5-Math.round(n)))+'</span>'}
async function boot(){
  const params=new URLSearchParams(location.search);
  if(params.get('reset')){ state.page='reset'; state.resetToken=params.get('reset'); }
  try{
    state.user=localStorage.getItem(tokenKey)?await api('/me'):null
  }catch(e){
    console.warn('Session could not be restored:',e)
    localStorage.removeItem(tokenKey)
    state.user=null
  }
  try{
    await loadProducts()
    state.bootError=null
  }catch(e){
    console.error('Marketplace API error:',e)
    state.products=[]
    state.bootError='Marketplace services are temporarily unavailable. Please try again shortly.'
  }
  render()
}
async function loadProducts(){const qs=new URLSearchParams();if(state.cat!=='All')qs.set('category',state.cat);const q=$('#search')?.value?.trim();if(q)qs.set('q',q);state.products=await api('/products?'+qs.toString())}
function nav(){return `<div class="topbar"><div class="shell">GLOBAL TRADE • ESCROW PROTECTED • VERIFIED SELLERS • 24/7 MARKETPLACE</div></div><div class="nav"><div class="shell navin"><div class="logo" onclick="go('home')">DEXILLIONZ<span>.</span></div><div class="search"><input id="search" placeholder="Search products, suppliers, categories..." onkeydown="if(event.key==='Enter')search()"><button class="dark" onclick="search()">SEARCH</button></div><div class="navlinks"><button onclick="go('home')">MARKET</button><button onclick="go('dashboard')">DASHBOARD</button><button onclick="go('chat')">CHAT</button><button onclick="go('disputes')">DISPUTES</button><button onclick="go('cart')">CART (${state.cart.length})</button>${state.user?`<button onclick="logout()">LOG OUT</button>`:`<button onclick="go('login')">SIGN IN</button>`}</div></div></div><div class="ticker"><div>⚡ LIVE TRADE • VERIFIED SUPPLIERS • ESCROW-STYLE PAYMENT PROTECTION • WHOLESALE QUOTES • REAL-TIME SUPPORT ⚡</div></div>`}
function home(){let list=state.products;let cats=['All',...new Set(state.products.map(p=>p.category))];return `<main class="shell"><section class="hero"><div class="heroCard"><div class="tag" style="background:var(--orange);color:var(--ink);align-self:flex-start">GLOBAL PULSE / 2026</div><h1>BUY BIG.<br><span>TRADE SMART.</span></h1><p>Industrial-grade global sourcing for businesses and consumers. Discover verified suppliers, negotiate bulk quotes, and transact through protected payment workflows.</p><div><button class="primary" onclick="document.getElementById('market').scrollIntoView()">EXPLORE MARKET</button> <button onclick="go('seller')">BECOME A SELLER</button></div></div><aside class="heroSide"><h2>MARKET PULSE</h2><div class="stat"><span>Active products</span><b>${list.length}+</b></div><div class="stat"><span>Verified sellers</span><b>ADMIN APPROVED</b></div><div class="stat"><span>Countries</span><b>GLOBAL</b></div><div class="stat"><span>Payment</span><b>PROTECTED</b></div></aside></section><section class="section" id="market">${state.bootError?`<div class="panel" style="margin-bottom:20px;border-color:var(--orange);background:#fff7ed"><h2>MARKETPLACE TEMPORARILY UNAVAILABLE</h2><p>${esc(state.bootError)}</p><button class="primary" onclick="location.reload()">TRY AGAIN</button></div>`:''}<div class="sectionHead"><h2>MARKET FLOOR</h2>${state.user?`<button onclick="go('dashboard')">OPEN CONTROL CENTER →</button>`:`<button onclick="go('login')">SIGN IN TO TRADE →</button>`}</div><div class="chips">${cats.map(c=>`<div class="chip ${state.cat===c?'active':''}" onclick="setCat('${esc(c)}')">${esc(c)}</div>`).join('')}</div><div class="grid" style="margin-top:20px">${list.map(card).join('')||'<div class="panel">No products found.</div>'}</div></section></main><footer class="footer"><div class="shell"><div class="logo">DEXILLIONZ<span>.</span></div><div>Global B2B/B2C commerce • Verified sellers • Protected payments • Quotes • Reviews • Live support</div></div></footer>`}
function card(p){return `<article class="card"><div class="pic">${p.image_url?`<img src="${esc(p.image_url)}" alt="${esc(p.name)}" style="width:100%;height:100%;object-fit:cover">`:emoji(p.category)}</div><div class="cardbody"><span class="tag">${esc(p.category)}</span><h3>${esc(p.name)}</h3><div>${stars(p.rating)} <b>${Number(p.rating||0).toFixed(1)}</b> <span class="meta">(${p.reviews})</span></div><div class="price">$${Number(p.price).toLocaleString()} <span class="meta">retail</span></div><div class="meta">Bulk from $${Number(p.bulk_price||p.price).toLocaleString()} • ${Number(p.stock).toLocaleString()} in stock<br>Seller: ${esc(p.seller)}</div><div class="cardfoot"><button onclick="go('product','${p.id}')">VIEW</button><button class="primary" onclick="add('${p.id}')">ADD TO CART</button></div></div></article>`}
function emoji(cat){return ({Vehicles:'🚙',Energy:'☀️',Food:'☕',Electronics:'💡',Construction:'🏗️',Beauty:'🧴',Machinery:'⚙️'})[cat]||'📦'}
async function product(id){let p=await api('/products/'+id);return `<main class="shell page"><div class="product"><div class="bigpic">${p.image_url?`<img src="${esc(p.image_url)}" alt="${esc(p.name)}" style="max-width:100%;max-height:500px;object-fit:contain">`:emoji(p.category)}</div><div class="panel"><span class="tag">VERIFIED SELLER • ${esc(p.category)}</span><h1 style="font-size:48px;margin:15px 0">${esc(p.name)}</h1><div class="rating">${stars(p.rating)} ${Number(p.rating||0).toFixed(1)} / 5 • ${p.reviews} verified reviews</div><p class="meta">Sold by <b>${esc(p.seller)}</b> • Ships globally • Protected payment eligible</p><hr><h2>Retail $${Number(p.price).toLocaleString()}</h2><p>Bulk price <b>$${Number(p.bulk_price||p.price).toLocaleString()}</b> from ${p.moq} units</p><div class="qty"><label>Quantity</label><input id="qty" type="number" min="1" max="${p.stock}" value="1"></div><div style="margin-top:18px"><button class="primary" onclick="buy('${p.id}')">BUY NOW → PAYMENT</button> <button onclick="quote('${p.id}')">REQUEST BULK QUOTE</button> <button onclick="openChat('${p.id}')">CHAT WITH SELLER</button></div><div class="notice" style="margin-top:20px">Payment is recorded against the order and seller funds are released only through the platform's delivery/dispute workflow. Actual regulated escrow/payment terms depend on the connected payment provider.</div></div></div><section class="section"><div class="sectionHead"><h2>BUYER REVIEWS</h2><button class="primary" onclick="reviewModal('${p.id}')">WRITE A REVIEW</button></div><div class="panel">${(p.reviews||[]).map(r=>`<div class="review"><b>${esc(r.name)}</b> ${stars(r.rating)}<p>${esc(r.body)}</p><small class="meta">${new Date(r.created_at).toLocaleString()}</small></div>`).join('')||'<p>No reviews yet. Verified buyers can review after delivery.</p>'}</div></section></main>`}
function cart(){let items=state.cart;let total=items.reduce((a,i)=>a+Number(i.price)*i.quantity,0);return `<main class="shell page"><div class="sectionHead"><h1>CART / CHECKOUT</h1><button onclick="go('home')">CONTINUE SHOPPING</button></div><div class="two"><div class="panel">${items.length?items.map((i,n)=>`<div class="review"><div style="display:flex;justify-content:space-between"><b>${emoji(i.category)} ${esc(i.name)}</b><b>$${(Number(i.price)*i.quantity).toLocaleString()}</b></div><small>${esc(i.seller)} • Qty ${i.quantity}</small><button class="ghost" onclick="removeCart(${n})">Remove</button></div>`).join(''):'<p>Your cart is empty.</p>'}</div><div class="panel"><h2>PROTECTED CHECKOUT</h2><div class="stat"><span>Items</span><b>$${total.toLocaleString()}</b></div><div class="stat"><span>Platform protection fee</span><b>$${(total*.015).toFixed(2)}</b></div><div class="stat"><span>Total</span><b>$${(total*1.015).toFixed(2)}</b></div><div class="notice">BUYER → PAYMENT PROVIDER → PLATFORM PROTECTION WORKFLOW → SELLER<br><small>Delivery confirmation or dispute handling controls the release workflow.</small></div><button class="primary" style="margin-top:18px;width:100%" onclick="checkout()">PLACE SECURE ORDER</button></div></div></main>`}
async function dashboard(){if(!state.user)return login();if(state.user.role==='admin')return adminDash();if(state.user.role==='seller')return sellerDash();let orders=await api('/orders');return `<main class="shell page"><h1>BUYER CONTROL CENTER</h1><div class="dashnav"><button onclick="go('dashboard')">ORDERS</button><button onclick="go('chat')">LIVE CHAT</button><button onclick="go('disputes')">DISPUTES</button></div><section class="section"><div class="panel"><h2>YOUR ORDERS</h2>${orders.length?orders.map(o=>`<div class="review"><b>#${o.id.slice(0,8).toUpperCase()}</b> • $${Number(o.total).toLocaleString()} • <span class="status ${o.status==='released'||o.status==='goods_released'?'resolved':'open'}">${esc(o.status).toUpperCase()}</span><div class="meta">Payment: ${esc(o.payment_status)} • Method: ${esc(o.payment_method)} • Protection: ${esc(o.escrow_status)}${o.dispute_deadline?` • Dispute deadline: ${new Date(o.dispute_deadline).toLocaleString()}`:''}</div>${o.payment_status==='unpaid'?`<button class="primary" onclick="payOrder('${o.id}')">VIEW PAYMENT INSTRUCTIONS</button>`:''}${o.payment_status==='paid'&&['paid','payment_confirmed','seller_payment_confirmed','in_fulfillment'].includes(o.status)?`<button class="primary" onclick="markDelivered('${o.id}')">CONFIRM DELIVERY & INSPECTION</button> <button onclick="disputeOrder('${o.id}')">OPEN DISPUTE</button>`:''}</div>`).join(''):'<p>No orders yet.</p>'}</div></section></main>`}
async function sellerDash(){let [q,orders]=await Promise.all([api('/seller/quotes'),api('/seller/orders')]);return `<main class="shell page"><h1>SELLER CENTER</h1><div class="dashnav"><button onclick="go('dashboard')">ORDERS & QUOTES</button><button onclick="go('seller-product')">LIST PRODUCT</button><button onclick="bankAccountModal()">BANK ACCOUNT</button><button onclick="go('chat')">BUYER CHAT</button><button onclick="go('disputes')">DISPUTES</button></div><div class="panel"><h2>ORDERS</h2>${orders.length?orders.map(o=>`<div class="review"><b>#${o.id.slice(0,8).toUpperCase()}</b> • $${Number(o.total).toLocaleString()} • ${esc(o.payment_method)} • ${esc(o.status)}<div class="meta">Payment: ${esc(o.payment_status)}${o.payment_reference?` • Ref: ${esc(o.payment_reference)}`:''}</div>${o.payment_method==='direct_wire'&&o.payment_status==='paid'&&o.status==='buyer_confirmed_delivery'?`<button class="primary" onclick="sellerConfirmWire('${o.id}')">CONFIRM BUYER PAYMENT RECEIVED</button>`:''}</div>`).join(''):'<p>No orders yet.</p>'}</div><div class="panel" style="margin-top:20px"><h2>QUOTE REQUESTS</h2>${q.length?q.map(x=>`<div class="review"><b>${esc(x.product)}</b> • ${x.quantity} units • ${esc(x.buyer)}<p>${esc(x.message)}</p><button class="primary" onclick="respondQuote('${x.id}','accepted')">ACCEPT</button> <button onclick="respondQuote('${x.id}','declined')">DECLINE</button></div>`).join(''):'<p>No quote requests.</p>'}</div></main>`}
async function adminDash(){let [stats,pending,pays,releasable]=await Promise.all([api('/admin/stats'),api('/admin/sellers/pending'),api('/admin/payments/pending'),api('/admin/orders/releasable')]);return `<main class="shell page"><h1>ADMIN CONTROL TOWER</h1><div class="dashnav"><button onclick="go('dashboard')">OVERVIEW</button><button onclick="go('chat')">CHAT</button><button onclick="go('disputes')">DISPUTES</button><button onclick="broadcast()">BULK EMAIL</button></div><div class="kpis"><div class="kpi">Users<b>${stats.users}</b></div><div class="kpi">Sellers<b>${stats.sellers}</b></div><div class="kpi">Products<b>${stats.products}</b></div><div class="kpi">Open disputes<b>${stats.open_disputes}</b></div></div><section class="section"><div class="two"><div class="panel"><h2>SELLER APPROVAL QUEUE</h2>${pending.length?pending.map(a=>`<div class="review"><b>${esc(a.business_name)}</b><p>${esc(a.name)} • ${esc(a.email)} • ${esc(a.country)}</p><p>${esc(a.description)}</p><button class="primary" onclick="approveSeller('${a.id}','approved')">APPROVE</button> <button onclick="approveSeller('${a.id}','rejected')">REJECT</button></div>`).join(''):'<p>No pending applications.</p>'}</div><div class="panel"><h2>PAYMENT VERIFICATION QUEUE</h2>${pays.length?pays.map(p=>`<div class="review"><b>#${p.id.slice(0,8).toUpperCase()}</b> • ${esc(p.payment_method)} • ${esc(p.reference)}<p>${esc(p.buyer)} • $${Number(p.total).toLocaleString()} ${esc(p.currency)} • ${esc(p.payment_transaction_status)}</p><button class="primary" onclick="confirmPayment('${p.id}')">CONFIRM RECEIPT</button></div>`).join(''):'<p>No payment reports awaiting verification.</p>'}<hr><h2>SELLER RELEASE QUEUE</h2>${releasable.length?releasable.map(o=>`<div class="review"><b>#${o.id.slice(0,8).toUpperCase()}</b> • $${Number(o.total).toLocaleString()} ${o.currency}<p>Dispute period expired. Eligible for seller release.</p><button class="primary" onclick="releaseOrder('${o.id}')">RELEASE SELLER SHARE</button></div>`).join(''):'<p>No orders are currently eligible for release.'}</div><div class="notice">Dexillionz controls the workflow and ledger. Actual custody/settlement of customer funds must be provided through an appropriately regulated banking/payment arrangement.</div></div></div></section></main>`}
function login(){return `<main class="shell page"><div class="panel" style="max-width:520px;margin:30px auto"><h1>SIGN IN</h1><div class="form"><input id="email" type="email" placeholder="Email"><input id="password" type="password" placeholder="Password"><button class="primary" onclick="loginNow()">ENTER MARKETPLACE</button><button class="ghost" onclick="forgotPasswordForm()">FORGOT PASSWORD?</button><button onclick="registerForm()">CREATE ACCOUNT</button></div></div></main>`}
function forgotPasswordForm(){modal(`<h2>RESET PASSWORD</h2><p class=\"meta\">Enter your account email and we'll send a secure reset link if the account exists.</p><div class=\"form\"><input id=\"femail\" type=\"email\" placeholder=\"Email\"><button class=\"primary\" onclick=\"requestPasswordReset()\">SEND RESET LINK</button></div>`)}
async function requestPasswordReset(){try{const email=$('#femail').value.trim();if(!email)return alert('Enter your email address.');const d=await api('/auth/forgot-password',{method:'POST',body:JSON.stringify({email})});closeModal();alert(d.message||'If an account exists for that email, a reset link has been sent.')}catch(e){alert(e.message)}}
function resetPasswordForm(){return `<main class=\"shell page\"><div class=\"panel\" style=\"max-width:520px;margin:30px auto\"><h1>CREATE NEW PASSWORD</h1><p class=\"meta\">Choose a new password with at least 8 characters.</p><div class=\"form\"><input id=\"newpass\" type=\"password\" placeholder=\"New password (8+ characters)\"><input id=\"confpass\" type=\"password\" placeholder=\"Confirm new password\"><button class=\"primary\" onclick=\"resetPasswordNow()\">RESET PASSWORD</button><button onclick=\"go('login')\">BACK TO SIGN IN</button></div></div></main>`}
async function resetPasswordNow(){try{const password=$('#newpass').value;const confirm=$('#confpass').value;if(password.length<8)return alert('Password must be at least 8 characters.');if(password!==confirm)return alert('Passwords do not match.');const d=await api('/auth/reset-password',{method:'POST',body:JSON.stringify({token:state.resetToken,password})});history.replaceState({},'',location.pathname);state.resetToken=null;alert(d.message);go('login')}catch(e){alert(e.message)}}

function registerForm(){modal(`<h2>CREATE ACCOUNT</h2><div class="form"><input id="rname" placeholder="Full name"><input id="remail" type="email" placeholder="Email"><input id="rpass" type="password" placeholder="Password (8+ characters)"><button class="primary" onclick="registerNow()">CREATE ACCOUNT</button></div>`)}
function seller(){if(!state.user)return login();return `<main class="shell page"><div class="panel" style="max-width:760px;margin:auto"><h1>SELLER APPLICATION</h1><p>Join Dexillionz as a verified supplier. Admin approval is required before products can be listed.</p><div class="form"><input id="biz" placeholder="Legal business name"><input id="bemail" placeholder="Business email"><input id="country" placeholder="Country / region"><textarea id="desc" placeholder="Describe your products, capacity and markets..."></textarea><button class="primary" onclick="submitSeller()">SUBMIT APPLICATION</button></div></div></main>`}
function sellerProduct(){return `<main class="shell page"><div class="panel" style="max-width:800px;margin:auto"><h1>LIST PRODUCT</h1><div class="form"><input id="pn" placeholder="Product name"><input id="pc" placeholder="Category"><textarea id="pd" placeholder="Product description"></textarea><input id="pp" type="number" step="0.01" placeholder="Retail price USD"><input id="pb" type="number" step="0.01" placeholder="Bulk price USD"><input id="pmoq" type="number" value="1" placeholder="MOQ"><input id="pst" type="number" value="0" placeholder="Stock"><input id="pi" placeholder="Image URL (optional)"><button class="primary" onclick="createProduct()">PUBLISH PRODUCT</button></div></div></main>`}
function modal(html){document.body.insertAdjacentHTML('beforeend',`<div class="modalback" id="modal"><div class="modal"><button class="ghost" style="float:right" onclick="closeModal()">✕</button>${html}</div></div>`)}function closeModal(){document.getElementById('modal')?.remove()}
async function loginNow(){try{const d=await api('/auth/login',{method:'POST',body:JSON.stringify({email:$('#email').value,password:$('#password').value})});localStorage.setItem(tokenKey,d.token);state.user=d.user;go('dashboard')}catch(e){alert(e.message)}}
async function registerNow(){try{const d=await api('/auth/register',{method:'POST',body:JSON.stringify({name:$('#rname').value,email:$('#remail').value,password:$('#rpass').value})});localStorage.setItem(tokenKey,d.token);state.user=d.user;closeModal();go('dashboard')}catch(e){alert(e.message)}}
async function logout(){localStorage.removeItem(tokenKey);state.user=null;state.conversations=[];state.conversation=null;go('home')}
async function add(id){let p=state.products.find(x=>x.id===id)||await api('/products/'+id);let x=state.cart.find(i=>i.id===id);if(x)x.quantity++;else state.cart.push({id:p.id,name:p.name,price:Number(p.price),category:p.category,seller:p.seller,quantity:1});save();render()}
function removeCart(i){state.cart.splice(i,1);save();render()}
async function buy(id){await add(id);go('cart')}
async function checkout(){if(!state.user)return go('login');if(!state.cart.length)return alert('Your cart is empty.');try{const paymentMethod=document.querySelector('input[name=pm]:checked')?.value||'platform_escrow';const o=await api('/orders',{method:'POST',body:JSON.stringify({items:state.cart.map(i=>({productId:i.id,quantity:i.quantity})),shippingAddress:{},paymentMethod})});state.cart=[];save();await showPayment(o.id)}catch(e){alert(e.message)}}
async function showPayment(id){const d=await api('/payments/'+id+'/instructions');let html=`<h2>${d.method==='platform_escrow'?'DEXILLIONZ PROTECTED PAYMENT':'DIRECT SELLER WIRE'}</h2><p>Order <b>#${id.slice(0,8).toUpperCase()}</b> • <b>${Number(d.amount).toLocaleString()} ${d.currency}</b></p><div class="notice">Payment reference: <b>${esc(d.reference)}</b><br>${esc(d.note)}</div>`;if(d.method==='platform_escrow'){html+=`<div class="review"><b>PAY TO DEXILLIONZ SECURE PAYMENTS</b><p>Bank: ${esc(d.beneficiary.bank||'Contact Dexillionz payment desk')}<br>Account name: ${esc(d.beneficiary.accountName||d.beneficiary.name)}<br>Account number: ${esc(d.beneficiary.accountNumber||'Available after secure onboarding')}<br>SWIFT: ${esc(d.beneficiary.swift||'')}<br>IBAN: ${esc(d.beneficiary.iban||'')}</p></div>`}else{html+=d.sellers.map(x=>`<div class="review"><b>${esc(x.business_name)}</b><p>Bank: ${esc(x.bank_name||'Seller has not supplied bank details')}<br>Account name: ${esc(x.account_name||'')}<br>Account number: ${esc(x.account_number||'')}<br>Routing: ${esc(x.routing_code||'')}<br>SWIFT: ${esc(x.swift||'')}<br>IBAN: ${esc(x.iban||'')}</p></div>`).join('')}html+=`<div class="form"><input id="payref" placeholder="Bank transfer reference (optional)"><input id="payproof" placeholder="Proof URL (optional)"><button class="primary" onclick="reportTransfer('${id}')">I HAVE SENT THE PAYMENT</button></div>`;modal(html)}
async function reportTransfer(id){try{await api('/payments/'+id+'/report-transfer',{method:'POST',body:JSON.stringify({bankReference:$('#payref').value,proofUrl:$('#payproof').value})});closeModal();alert('Payment reported. Dexillionz will verify the transaction before marking it confirmed.');go('dashboard')}catch(e){alert(e.message)}}
async function payOrder(id){showPayment(id)}
async function quote(id){if(!state.user)return go('login');let p=state.products.find(x=>x.id===id)||await api('/products/'+id);modal(`<h2>BULK QUOTE • ${esc(p.name)}</h2><div class="form"><input id="qqty" type="number" value="${p.moq||20}" min="${p.moq||1}"><input id="qprice" type="number" step="0.01" placeholder="Target unit price (optional)"><textarea id="qmsg" placeholder="Destination, timeline and requirements..."></textarea><button class="primary" onclick="sendQuote('${p.id}')">SEND QUOTE REQUEST</button></div>`)}
async function sendQuote(id){try{await api('/quotes',{method:'POST',body:JSON.stringify({productId:id,quantity:+$('#qqty').value,targetPrice:$('#qprice').value?+$('#qprice').value:null,message:$('#qmsg').value})});closeModal();alert('Quote request sent to the supplier.')}catch(e){alert(e.message)}}
async function reviewModal(id){if(!state.user)return go('login');modal(`<h2>WRITE A REVIEW</h2><div class="form"><input id="roid" placeholder="Delivered order ID"><select id="rstar"><option>5</option><option>4</option><option>3</option><option>2</option><option>1</option></select><textarea id="rtext" placeholder="Share your verified purchase experience..."></textarea><button class="primary" onclick="publishReview('${id}')">PUBLISH VERIFIED REVIEW</button></div>`)}
async function publishReview(id){try{await api('/reviews',{method:'POST',body:JSON.stringify({productId:id,orderId:$('#roid').value.trim(),rating:+$('#rstar').value,body:$('#rtext').value})});closeModal();alert('Verified review published.');render()}catch(e){alert(e.message)}}
async function openChat(productId){if(!state.user)return go('login');let p=await api('/products/'+productId);let seller=(await api('/products/'+productId));try{const c=await api('/conversations',{method:'POST',body:JSON.stringify({sellerId:p.seller_id,productId})});state.conversation=c.id;go('chat')}catch(e){alert(e.message)}}
async function selectConversation(id){state.conversation=id;await render()}
async function sendMsg(){if(!state.conversation)return alert('Open a product chat first.');let body=$('#msg').value.trim();if(!body)return;try{await api('/conversations/'+state.conversation+'/messages',{method:'POST',body:JSON.stringify({body})});await render()}catch(e){alert(e.message)}}
async function submitSeller(){try{await api('/seller/apply',{method:'POST',body:JSON.stringify({businessName:$('#biz').value,country:$('#country').value,businessEmail:$('#bemail').value,description:$('#desc').value})});alert('Application submitted for admin approval.');go('dashboard')}catch(e){alert(e.message)}}
async function createProduct(){try{await api('/seller/products',{method:'POST',body:JSON.stringify({name:$('#pn').value,category:$('#pc').value,description:$('#pd').value,price:+$('#pp').value,bulkPrice:$('#pb').value?+$('#pb').value:null,moq:+$('#pmoq').value,stock:+$('#pst').value,imageUrl:$('#pi').value||null})});alert('Product published.');go('dashboard')}catch(e){alert(e.message)}}
async function bankAccountModal(){modal(`<h2>SELLER BANK ACCOUNT</h2><div class="form"><input id="bn" placeholder="Bank name"><input id="ba" placeholder="Account name"><input id="bac" placeholder="Account number"><input id="br" placeholder="Routing code"><input id="bsw" placeholder="SWIFT"><input id="bib" placeholder="IBAN"><input id="bc" value="USD" placeholder="Currency"><button class="primary" onclick="saveBank()">SAVE BANK DETAILS</button></div>`)}
async function saveBank(){try{await api('/seller/bank-account',{method:'POST',body:JSON.stringify({bankName:$('#bn').value,accountName:$('#ba').value,accountNumber:$('#bac').value,routingCode:$('#br').value,swiftCode:$('#bsw').value,iban:$('#bib').value,currency:$('#bc').value})});closeModal();alert('Bank details saved. They remain unverified until admin review.')}catch(e){alert(e.message)}}
async function releaseOrder(id){try{await api('/admin/orders/'+id+'/force-release',{method:'POST'});alert('Seller release recorded. Connect your regulated settlement/banking rail to execute the actual bank transfer.');render()}catch(e){alert(e.message)}}
async function confirmPayment(id){try{await api('/admin/payments/'+id+'/confirm',{method:'POST'});render()}catch(e){alert(e.message)}}
async function sellerConfirmWire(id){try{await api('/seller/orders/'+id+'/confirm-direct-payment',{method:'POST'});alert('Payment receipt confirmed. The order is now ready for authorized agent release.');render()}catch(e){alert(e.message)}}
async function respondQuote(id,status){try{await api('/quotes/'+id,{method:'PATCH',body:JSON.stringify({status})});render()}catch(e){alert(e.message)}}
async function approveSeller(id,status){try{await api('/admin/sellers/'+id,{method:'PATCH',body:JSON.stringify({status})});render()}catch(e){alert(e.message)}}
async function markDelivered(id){try{await api('/orders/'+id+'/delivery',{method:'POST'});render()}catch(e){alert(e.message)}}
async function disputeOrder(id){disputeModal(id)}
function disputeModal(orderId=''){if(!state.user)return go('login');modal(`<h2>OPEN DISPUTE</h2><div class="form"><input id="did" value="${esc(orderId)}" placeholder="Order ID"><select id="dreason"><option>Damaged goods</option><option>Wrong item</option><option>Not delivered</option><option>Other</option></select><textarea id="ddesc" placeholder="Explain the issue and desired resolution..."></textarea><button class="primary" onclick="openDispute()">OPEN CASE</button></div>`)}
async function openDispute(){try{await api('/disputes',{method:'POST',body:JSON.stringify({orderId:$('#did').value.trim(),reason:$('#dreason').value,description:$('#ddesc').value})});closeModal();alert('Dispute opened. The order protection workflow has been activated.');go('disputes')}catch(e){alert(e.message)}}
async function resolveDispute(id){let resolution=prompt('Enter resolution (refund, release, split, etc.):');if(!resolution)return;try{await api('/disputes/'+id,{method:'PATCH',body:JSON.stringify({status:'resolved',resolution})});render()}catch(e){alert(e.message)}}
function broadcast(){if(state.user?.role!=='admin')return alert('Admin access required.');modal(`<h2>BULK EMAIL BROADCAST</h2><div class="form"><select id="ba"><option value="all">All users</option><option value="buyers">Buyers</option><option value="sellers">Sellers</option></select><input id="bs" placeholder="Subject"><textarea id="bb" placeholder="Write your marketplace announcement..."></textarea><button class="primary" onclick="sendBroadcast()">SEND BROADCAST</button></div>`)}
async function sendBroadcast(){try{const r=await api('/admin/broadcasts',{method:'POST',body:JSON.stringify({audience:$('#ba').value,subject:$('#bs').value,body:$('#bb').value})});closeModal();alert(r.status==='sent'?'Broadcast sent successfully.':'Broadcast recorded. Configure RESEND_API_KEY to deliver email.')}catch(e){alert(e.message)}}
async function search(){await loadProducts();go('home')}
async function setCat(c){state.cat=c;await loadProducts();render()}
function go(page,id=null){state.page=page;state.id=id;render();scrollTo(0,0)}
async function render(){try{let body;if(state.page==='home')body=home();else if(state.page==='product')body=await product(state.id);else if(state.page==='cart')body=cart();else if(state.page==='dashboard')body=await dashboard();else if(state.page==='chat')body=await chat();else if(state.page==='disputes')body=await disputes();else if(state.page==='login')body=login();else if(state.page==='reset')body=resetPasswordForm();else if(state.page==='seller')body=seller();else if(state.page==='seller-product')body=sellerProduct();else body=home();document.getElementById('app').innerHTML=nav()+body}catch(e){document.getElementById('app').innerHTML=nav()+`<main class="shell page"><div class="panel"><h2>Something went wrong</h2><p>${esc(e.message)}</p></div></main>`}}
boot();
