require('dotenv').config();
const express=require('express'),http=require('http'),path=require('path'),cors=require('cors'),helmet=require('helmet'),rateLimit=require('express-rate-limit');
const {Server}=require('socket.io'); const crypto=require('crypto'); const {query,pool}=require('./db'); const {sign,hash,compare,requireAuth,requireRole}=require('./auth'); const {Resend}=require('resend');
const app=express(),server=http.createServer(app);
const APP_URL=process.env.APP_URL||'https://dexillionzglobal.com'; const allowedOrigins=(process.env.CORS_ORIGIN||APP_URL+',https://dexillionzglobalmarketplace.onrender.com').split(',').map(x=>x.trim()).filter(Boolean); const corsOrigin=(origin,cb)=>{if(!origin||allowedOrigins.includes('*')||allowedOrigins.includes(origin))return cb(null,true); cb(new Error('CORS origin not allowed'))}; const io=new Server(server,{cors:{origin:corsOrigin}}); const resend=process.env.RESEND_API_KEY?new Resend(process.env.RESEND_API_KEY):null;
const PROTECTION_RATE=Number(process.env.PROTECTION_FEE_RATE||0.015); const DISPUTE_DAYS=Number(process.env.DISPUTE_PERIOD_DAYS||3);
app.use(helmet({contentSecurityPolicy:false})); app.use(cors({origin:corsOrigin})); app.use(express.json({limit:'1mb'})); app.use(rateLimit({windowMs:15*60*1000,max:500}));
const asyncRoute=fn=>(req,res,next)=>Promise.resolve(fn(req,res,next)).catch(next); const money=n=>Number(Number(n).toFixed(2));
async function getOrder(id,userId){return (await query('select * from orders where id=$1 and buyer_id=$2',[id,userId])).rows[0]}
async function releaseEligibleOrder(orderId,actorId){
 const o=(await query("select * from orders where id=$1 and payment_status='paid'",[orderId])).rows[0]; if(!o) throw new Error('Paid order not found');
 const active=(await query("select 1 from disputes where order_id=$1 and status!='resolved'",[orderId])).rowCount; if(active) throw new Error('Order has an open dispute');
 if(!o.delivery_confirmed_at) throw new Error('Buyer has not confirmed delivery');
 if(o.dispute_deadline && new Date(o.dispute_deadline)>new Date()) throw new Error('Dispute period has not expired');
 const groups=(await query(`select oi.seller_id,round(sum(oi.quantity*oi.unit_price),2) amount from order_items oi where oi.order_id=$1 group by oi.seller_id`,[orderId])).rows;
 const client=await pool.connect(); try{await client.query('begin');
   for(const g of groups){const exists=(await client.query('select id from seller_releases where order_id=$1 and seller_id=$2',[orderId,g.seller_id])).rows[0]; if(exists)continue;
     await client.query("insert into seller_releases(order_id,seller_id,amount,status,released_by,released_at) values($1,$2,$3,'released',$4,now())",[orderId,g.seller_id,g.amount,actorId]);
     await client.query("insert into payment_ledger(order_id,seller_id,entry_type,amount,currency,reference) values($1,$2,'seller_release',$3,$4,$5)",[orderId,g.seller_id,g.amount,o.currency,'REL-'+orderId.slice(0,8)+'-'+g.seller_id.slice(0,8)]);
   }
   await client.query("update orders set status='released',escrow_status='released',released_at=now() where id=$1",[orderId]); await client.query('commit');
 }catch(e){await client.query('rollback');throw e}finally{client.release()}
 return (await query('select * from orders where id=$1',[orderId])).rows[0];
}
app.get('/api/health',(req,res)=>res.json({ok:true,service:'dexillionz-api',payment_system:'dexillionz-secure-payments',time:new Date().toISOString()}));
app.post('/api/auth/register',asyncRoute(async(req,res)=>{const {name,email,password}=req.body;if(!name||!email||!password||password.length<8)return res.status(400).json({error:'Name, valid email and password (8+ chars) required'});const exists=await query('select id from users where lower(email)=lower($1)',[email]);if(exists.rowCount)return res.status(409).json({error:'Email already registered'});const u=(await query('insert into users(name,email,password_hash) values($1,$2,$3) returning id,name,email,role',[name.trim(),email.toLowerCase(),await hash(password)])).rows[0];res.status(201).json({user:u,token:sign(u)})}));
app.post('/api/auth/login',asyncRoute(async(req,res)=>{const {email,password}=req.body;const r=await query('select * from users where lower(email)=lower($1)',[email]);if(!r.rowCount||!(await compare(password,r.rows[0].password_hash)))return res.status(401).json({error:'Invalid email or password'});const u=r.rows[0];res.json({user:{id:u.id,name:u.name,email:u.email,role:u.role},token:sign(u)})}));
app.post('/api/auth/forgot-password',asyncRoute(async(req,res)=>{
 const email=String(req.body?.email||'').trim().toLowerCase();
 const generic={message:'If an account exists for that email, a password reset link has been sent.'};
 if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) return res.json(generic);
 const user=(await query('select id,name,email from users where lower(email)=lower($1)',[email])).rows[0];
 if(!user) return res.json(generic);
 await query("delete from password_reset_tokens where user_id=$1 or expires_at < now()",[user.id]);
 const token=crypto.randomBytes(32).toString('hex');
 const tokenHash=crypto.createHash('sha256').update(token).digest('hex');
 await query("insert into password_reset_tokens(user_id,token_hash,expires_at) values($1,$2,now()+interval '1 hour')",[user.id,tokenHash]);
 if(resend){
   const resetUrl=APP_URL.replace(/\/$/,'')+'/?reset='+encodeURIComponent(token);
   await resend.emails.send({from:process.env.EMAIL_FROM,to:user.email,subject:'Reset your Dexillionz password',html:`<div style=\"font-family:Arial,sans-serif;line-height:1.6\"><h2>Password reset</h2><p>Hello ${String(user.name||'there').replace(/[&<>\"']/g,'')},</p><p>We received a request to reset your Dexillionz password. This link expires in 1 hour.</p><p><a href=\"${resetUrl}\" style=\"display:inline-block;padding:12px 18px;background:#111;color:#fff;text-decoration:none;border-radius:6px\">RESET PASSWORD</a></p><p>If you did not request this, you can ignore this email.</p></div>`});
 } else {
   console.warn('Password reset requested but RESEND_API_KEY is not configured for',user.email);
 }
 res.json(generic);
}));
app.post('/api/auth/reset-password',asyncRoute(async(req,res)=>{
 const token=String(req.body?.token||'').trim(); const password=String(req.body?.password||'');
 if(!token||token.length<32) return res.status(400).json({error:'Invalid or expired reset link'});
 if(password.length<8) return res.status(400).json({error:'Password must be at least 8 characters'});
 const tokenHash=crypto.createHash('sha256').update(token).digest('hex');
 const r=await query('select u.id,u.name,u.email,u.role,t.id token_id from password_reset_tokens t join users u on u.id=t.user_id where t.token_hash=$1 and t.used_at is null and t.expires_at>now()',[tokenHash]);
 if(!r.rowCount) return res.status(400).json({error:'Invalid or expired reset link'});
 const u=r.rows[0]; const passwordHash=await hash(password);
 const client=await pool.connect();
 try{await client.query('begin'); await client.query('update users set password_hash=$1 where id=$2',[passwordHash,u.id]); await client.query('update password_reset_tokens set used_at=now() where user_id=$1 and used_at is null',[u.id]); await client.query('commit')}catch(e){await client.query('rollback');throw e}finally{client.release()}
 res.json({message:'Password reset successfully. You can now sign in.'});
}));
app.get('/api/me',requireAuth,asyncRoute(async(req,res)=>res.json((await query('select id,name,email,role,status,email_verified from users where id=$1',[req.user.sub])).rows[0])));
app.get('/api/products',asyncRoute(async(req,res)=>{const {q,category}=req.query;const vals=[];let where='p.active=true';if(category){vals.push(category);where+=' and p.category=$'+vals.length}if(q){vals.push('%'+q+'%');where+=' and (p.name ilike $'+vals.length+' or p.description ilike $'+vals.length+')'}const r=await query(`select p.*,s.business_name seller,coalesce(round(avg(rv.rating),1),0) rating,count(rv.id)::int reviews from products p join sellers s on s.id=p.seller_id left join reviews rv on rv.product_id=p.id where ${where} group by p.id,s.business_name order by p.created_at desc`,vals);res.json(r.rows)}));
app.get('/api/products/:id',asyncRoute(async(req,res)=>{const p=await query(`select p.*,s.business_name seller,coalesce(round(avg(rv.rating),1),0) rating,count(rv.id)::int reviews from products p join sellers s on s.id=p.seller_id left join reviews rv on rv.product_id=p.id where p.id=$1 group by p.id,s.business_name`,[req.params.id]);if(!p.rowCount)return res.status(404).json({error:'Product not found'});const rv=await query('select r.id,r.rating,r.body,r.created_at,u.name from reviews r join users u on u.id=r.buyer_id where r.product_id=$1 order by r.created_at desc',[req.params.id]);res.json({...p.rows[0],reviews:rv.rows})}));
app.post('/api/seller/apply',requireAuth,asyncRoute(async(req,res)=>{const {businessName,country,businessEmail,description}=req.body;const r=await query('insert into seller_applications(user_id,business_name,country,business_email,description) values($1,$2,$3,$4,$5) returning *',[req.user.sub,businessName,country,businessEmail,description||'']);res.status(201).json(r.rows[0])}));
app.post('/api/seller/products',requireAuth,requireRole('seller','admin'),asyncRoute(async(req,res)=>{const {name,category,description,price,bulkPrice,moq,stock,currency,imageUrl}=req.body;const s=await query('select id from sellers where user_id=$1',[req.user.sub]);if(!s.rowCount)return res.status(403).json({error:'Seller account not approved'});const r=await query('insert into products(seller_id,name,category,description,price,bulk_price,moq,stock,currency,image_url) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) returning *',[s.rows[0].id,name,category,description,price,bulkPrice||null,moq||1,stock||0,currency||'USD',imageUrl||null]);res.status(201).json(r.rows[0])}));
app.post('/api/seller/bank-account',requireAuth,requireRole('seller','admin'),asyncRoute(async(req,res)=>{const s=(await query('select id from sellers where user_id=$1',[req.user.sub])).rows[0];if(!s)return res.status(403).json({error:'Seller not approved'});const {bankName,accountName,accountNumber,routingCode,swiftCode,iban,currency}=req.body;const r=await query(`insert into seller_bank_accounts(seller_id,bank_name,account_name,account_number,routing_code,swift_code,iban,currency) values($1,$2,$3,$4,$5,$6,$7,$8) on conflict(seller_id) do update set bank_name=excluded.bank_name,account_name=excluded.account_name,account_number=excluded.account_number,routing_code=excluded.routing_code,swift_code=excluded.swift_code,iban=excluded.iban,currency=excluded.currency,verified=false returning id,bank_name,account_name,account_number,routing_code,swift_code,iban,currency,verified`,[s.id,bankName,accountName,accountNumber,routingCode||null,swiftCode||null,iban||null,currency||'USD']);res.json(r.rows[0])}));
app.get('/api/seller/orders',requireAuth,requireRole('seller','admin'),asyncRoute(async(req,res)=>{const r=await query(`select distinct o.*,pt.reference payment_reference from orders o join order_items oi on oi.order_id=o.id join sellers s on s.id=oi.seller_id left join payment_transactions pt on pt.order_id=o.id where s.user_id=$1 order by o.created_at desc`,[req.user.sub]);res.json(r.rows)}));
app.get('/api/seller/quotes',requireAuth,requireRole('seller','admin'),asyncRoute(async(req,res)=>{const s=await query('select id from sellers where user_id=$1',[req.user.sub]);if(!s.rowCount)return res.json([]);res.json((await query('select q.*,p.name product,u.name buyer,u.email from quotes q join products p on p.id=q.product_id join users u on u.id=q.buyer_id where p.seller_id=$1 order by q.created_at desc',[s.rows[0].id])).rows)}));
app.post('/api/quotes',requireAuth,asyncRoute(async(req,res)=>{const {productId,quantity,targetPrice,message}=req.body;const r=await query('insert into quotes(buyer_id,product_id,quantity,unit_price_target,message) values($1,$2,$3,$4,$5) returning *',[req.user.sub,productId,quantity,targetPrice||null,message]);res.status(201).json(r.rows[0])}));
app.patch('/api/quotes/:id',requireAuth,requireRole('seller','admin'),asyncRoute(async(req,res)=>{const {status,sellerMessage}=req.body;const r=await query(`update quotes q set status=$1,seller_message=$2 from products p,sellers s where q.id=$3 and q.product_id=p.id and p.seller_id=s.id and s.user_id=$4 returning q.*`,[status,sellerMessage||null,req.params.id,req.user.sub]);if(!r.rowCount)return res.status(404).json({error:'Quote not found'});res.json(r.rows[0])}));
app.get('/api/orders',requireAuth,asyncRoute(async(req,res)=>{const r=await query(`select o.*,pt.status payment_transaction_status,pt.reference payment_reference from orders o left join payment_transactions pt on pt.order_id=o.id where o.buyer_id=$1 order by o.created_at desc`,[req.user.sub]);res.json(r.rows)}));
app.get('/api/orders/:id',requireAuth,asyncRoute(async(req,res)=>{const o=await getOrder(req.params.id,req.user.sub);if(!o)return res.status(404).json({error:'Order not found'});const items=await query('select oi.*,p.name,s.business_name seller from order_items oi join products p on p.id=oi.product_id join sellers s on s.id=oi.seller_id where oi.order_id=$1',[o.id]);const pt=await query('select id,method,status,reference,amount,currency,bank_reference,confirmed_at from payment_transactions where order_id=$1',[o.id]);res.json({...o,items:items.rows,payment:pt.rows[0]||null})}));
app.post('/api/orders',requireAuth,asyncRoute(async(req,res)=>{const {items,shippingAddress,paymentMethod='platform_escrow'}=req.body;if(!Array.isArray(items)||!items.length)return res.status(400).json({error:'Cart is empty'});if(!['platform_escrow','direct_wire'].includes(paymentMethod))return res.status(400).json({error:'Invalid payment method'});const ids=items.map(x=>x.productId);const ps=await query('select * from products where id=any($1::uuid[]) and active=true',[ids]);const map=new Map(ps.rows.map(p=>[p.id,p]));let subtotal=0;for(const i of items){const p=map.get(i.productId);if(!p||i.quantity<1||i.quantity>p.stock)return res.status(400).json({error:'Invalid item or stock'});subtotal+=Number(p.price)*i.quantity}const fee=money(subtotal*PROTECTION_RATE);const total=money(subtotal+fee);const client=await pool.connect();try{await client.query('begin');const o=(await client.query('insert into orders(buyer_id,subtotal,protection_fee,total,shipping_address,payment_method) values($1,$2,$3,$4,$5,$6) returning *',[req.user.sub,subtotal,fee,total,shippingAddress||{},paymentMethod])).rows[0];for(const i of items){const p=map.get(i.productId);await client.query('insert into order_items(order_id,product_id,seller_id,quantity,unit_price) values($1,$2,$3,$4,$5)',[o.id,p.id,i.quantity,p.seller_id,p.price]);await client.query('update products set stock=stock-$1 where id=$2',[i.quantity,p.id])}const ref=(paymentMethod==='platform_escrow'?'DX-ESC-':'DX-WIR-')+o.id.replaceAll('-','').slice(0,16).toUpperCase();await client.query('insert into payment_transactions(order_id,method,status,reference,amount,currency,payer_id) values($1,$2,$3,$4,$5,$6,$7)',[o.id,paymentMethod,'awaiting_payment',ref,total,o.currency,req.user.sub]);await client.query('commit');res.status(201).json(o)}catch(e){await client.query('rollback');throw e}finally{client.release()}}));
app.get('/api/payments/config',requireAuth,asyncRoute(async(req,res)=>res.json({platformEscrowEnabled:true,directWireEnabled:true,protectionFeeRate:PROTECTION_RATE,disputePeriodDays:DISPUTE_DAYS,platformBeneficiaryName:process.env.PAYMENT_BENEFICIARY_NAME||'Dexillionz Global Secure Payments',platformBankName:process.env.PAYMENT_BANK_NAME||'',platformAccountName:process.env.PAYMENT_ACCOUNT_NAME||'',platformAccountNumber:process.env.PAYMENT_ACCOUNT_NUMBER||'',platformRoutingCode:process.env.PAYMENT_ROUTING_CODE||'',platformSwift:process.env.PAYMENT_SWIFT||'',platformIban:process.env.PAYMENT_IBAN||''})));
app.get('/api/payments/:orderId/instructions',requireAuth,asyncRoute(async(req,res)=>{const o=await getOrder(req.params.orderId,req.user.sub);if(!o)return res.status(404).json({error:'Order not found'});const pt=(await query('select * from payment_transactions where order_id=$1',[o.id])).rows[0];if(!pt)return res.status(404).json({error:'Payment transaction not found'});if(pt.method==='platform_escrow')return res.json({method:pt.method,reference:pt.reference,amount:o.total,currency:o.currency,beneficiary:{name:process.env.PAYMENT_BENEFICIARY_NAME||'Dexillionz Global Secure Payments',bank:process.env.PAYMENT_BANK_NAME||'',accountName:process.env.PAYMENT_ACCOUNT_NAME||'',accountNumber:process.env.PAYMENT_ACCOUNT_NUMBER||'',routingCode:process.env.PAYMENT_ROUTING_CODE||'',swift:process.env.PAYMENT_SWIFT||'',iban:process.env.PAYMENT_IBAN||''},note:'Use the exact payment reference. Payment is not treated as confirmed until the platform verifies receipt.'});const sellers=(await query(`select distinct s.id,s.business_name,sba.bank_name,sba.account_name,sba.account_number,sba.routing_code,sba.swift_code,sba.iban,sba.currency from order_items oi join sellers s on s.id=oi.seller_id left join seller_bank_accounts sba on sba.seller_id=s.id where oi.order_id=$1`,[o.id])).rows;res.json({method:pt.method,reference:pt.reference,amount:o.total,currency:o.currency,sellers,note:'Buyer wires the agreed amount directly to the seller. Seller confirms receipt, then an authorized Dexillionz agent releases the goods.'})}));
app.post('/api/payments/:orderId/report-transfer',requireAuth,asyncRoute(async(req,res)=>{const o=await getOrder(req.params.orderId,req.user.sub);if(!o)return res.status(404).json({error:'Order not found'});const {bankReference,proofUrl}=req.body;const r=await query("update payment_transactions set status='reported',bank_reference=$1,proof_url=$2,updated_at=now() where order_id=$3 and payer_id=$4 returning id,reference,status,bank_reference,proof_url",[bankReference||null,proofUrl||null,o.id,req.user.sub]);if(!r.rowCount)return res.status(404).json({error:'Payment transaction not found'});res.json(r.rows[0])}));
app.post('/api/seller/orders/:orderId/confirm-direct-payment',requireAuth,requireRole('seller','admin'),asyncRoute(async(req,res)=>{const o=(await query("select o.* from orders o join order_items oi on oi.order_id=o.id join sellers s on s.id=oi.seller_id where o.id=$1 and o.payment_method='direct_wire' and s.user_id=$2 and o.payment_status='paid'",[req.params.orderId,req.user.sub])).rows[0];if(!o)return res.status(404).json({error:'Direct-wire order not found or not assigned to you'});await query("update orders set status='seller_payment_confirmed' where id=$1",[o.id]);res.json((await query('select * from orders where id=$1',[o.id])).rows[0])}));
app.get('/api/admin/payments/pending',requireAuth,requireRole('admin'),asyncRoute(async(req,res)=>res.json((await query("select o.id,o.total,o.currency,o.payment_method,o.status,o.payment_status,o.created_at,pt.reference,pt.status payment_transaction_status,u.name buyer,u.email from orders o join users u on u.id=o.buyer_id join payment_transactions pt on pt.order_id=o.id where pt.status in ('reported','awaiting_payment') order by o.created_at desc")).rows)));
app.post('/api/admin/payments/:orderId/confirm',requireAuth,requireRole('admin'),asyncRoute(async(req,res)=>{const o=(await query('select * from orders where id=$1',[req.params.orderId])).rows[0];if(!o)return res.status(404).json({error:'Order not found'});const pt=(await query('select * from payment_transactions where order_id=$1',[o.id])).rows[0];if(!pt)return res.status(404).json({error:'Payment not found'});await query("update payment_transactions set status='confirmed',confirmed_by=$1,confirmed_at=now(),updated_at=now() where id=$2",[req.user.sub,pt.id]);if(pt.method==='platform_escrow')await query("update orders set payment_status='paid',status='paid',escrow_status='funded',dispute_deadline=null where id=$1",[o.id]);else await query("update orders set payment_status='paid',status='payment_confirmed',escrow_status='direct_payment' where id=$1",[o.id]);await query('insert into payment_ledger(order_id,entry_type,amount,currency,reference) values($1,\'buyer_funding\',$2,$3,$4)',[o.id,o.total,o.currency,pt.reference]);res.json((await query('select * from orders where id=$1',[o.id])).rows[0])}));
app.post('/api/orders/:id/delivery',requireAuth,asyncRoute(async(req,res)=>{const o=await getOrder(req.params.id,req.user.sub);if(!o||o.payment_status!=='paid')return res.status(400).json({error:'Order is not paid'});const active=(await query("select 1 from disputes where order_id=$1 and status!='resolved'",[o.id])).rowCount;if(active)return res.status(409).json({error:'Order has an open dispute'});const deadline=new Date(Date.now()+DISPUTE_DAYS*86400000);if(o.payment_method==='direct_wire'){await query("update orders set status='buyer_confirmed_delivery',delivery_confirmed_at=now(),inspection_confirmed_at=now(),dispute_deadline=$2 where id=$1",[o.id,deadline]);return res.json((await query('select * from orders where id=$1',[o.id])).rows[0])}await query("update orders set status='delivery_confirmed',delivery_confirmed_at=now(),inspection_confirmed_at=now(),dispute_deadline=$2 where id=$1",[o.id,deadline]);res.json((await query('select * from orders where id=$1',[o.id])).rows[0])}));
app.post('/api/orders/:id/release',requireAuth,asyncRoute(async(req,res)=>{const o=await getOrder(req.params.id,req.user.sub);if(!o)return res.status(404).json({error:'Order not found'});try{res.json(await releaseEligibleOrder(o.id,req.user.sub))}catch(e){res.status(409).json({error:e.message})}}));
app.get('/api/admin/orders/releasable',requireAuth,requireRole('admin'),asyncRoute(async(req,res)=>res.json((await query("select o.id,o.total,o.currency,o.payment_method,o.status,o.dispute_deadline from orders o where o.payment_method='platform_escrow' and o.payment_status='paid' and o.delivery_confirmed_at is not null and o.dispute_deadline is not null and o.dispute_deadline<=now() and not exists(select 1 from disputes d where d.order_id=o.id and d.status!='resolved') and not exists(select 1 from seller_releases sr where sr.order_id=o.id) order by o.dispute_deadline")).rows)));
app.post('/api/admin/orders/:id/force-release',requireAuth,requireRole('admin'),asyncRoute(async(req,res)=>{try{res.json(await releaseEligibleOrder(req.params.id,req.user.sub))}catch(e){res.status(409).json({error:e.message})}}));
app.post('/api/admin/orders/:id/direct-payment-release',requireAuth,requireRole('admin'),asyncRoute(async(req,res)=>{const o=(await query("select * from orders where id=$1 and payment_method='direct_wire' and payment_status='paid'",[req.params.id])).rows[0];if(!o)return res.status(404).json({error:'Direct-payment order not found'});await query("update orders set status='goods_released',released_at=now() where id=$1",[o.id]);res.json((await query('select * from orders where id=$1',[o.id])).rows[0])}));
app.post('/api/reviews',requireAuth,asyncRoute(async(req,res)=>{const {productId,orderId,rating,body}=req.body;const ok=await query(`select 1 from order_items oi join orders o on o.id=oi.order_id where oi.product_id=$1 and o.id=$2 and o.buyer_id=$3 and o.status in('released','goods_released')`,[productId,orderId,req.user.sub]);if(!ok.rowCount)return res.status(403).json({error:'Only completed purchases can be reviewed'});const r=await query('insert into reviews(product_id,buyer_id,order_id,rating,body) values($1,$2,$3,$4,$5) returning *',[productId,req.user.sub,orderId,rating,body]);res.status(201).json(r.rows[0])}));
app.post('/api/conversations',requireAuth,asyncRoute(async(req,res)=>{const {sellerId,productId}=req.body;const r=await query(`insert into conversations(buyer_id,seller_id,product_id) values($1,$2,$3) on conflict(buyer_id,seller_id,product_id) do update set product_id=excluded.product_id returning *`,[req.user.sub,sellerId,productId||null]);res.status(201).json(r.rows[0])}));
app.get('/api/conversations',requireAuth,asyncRoute(async(req,res)=>res.json((await query(`select c.*,s.business_name seller from conversations c join sellers s on s.id=c.seller_id where c.buyer_id=$1 or s.user_id=$1 order by c.created_at desc`,[req.user.sub])).rows)));
app.get('/api/conversations/:id/messages',requireAuth,asyncRoute(async(req,res)=>{const c=await query(`select c.id from conversations c join sellers s on s.id=c.seller_id where c.id=$1 and (c.buyer_id=$2 or s.user_id=$2)`,[req.params.id,req.user.sub]);if(!c.rowCount)return res.status(403).json({error:'Not a conversation member'});res.json((await query('select m.*,u.name from messages m join users u on u.id=m.sender_id where m.conversation_id=$1 order by m.created_at',[req.params.id])).rows)}));
app.post('/api/conversations/:id/messages',requireAuth,asyncRoute(async(req,res)=>{const c=await query(`select c.id from conversations c join sellers s on s.id=c.seller_id where c.id=$1 and (c.buyer_id=$2 or s.user_id=$2)`,[req.params.id,req.user.sub]);if(!c.rowCount)return res.status(403).json({error:'Not a conversation member'});const r=await query('insert into messages(conversation_id,sender_id,body) values($1,$2,$3) returning *',[req.params.id,req.user.sub,req.body.body]);io.to(req.params.id).emit('message',r.rows[0]);res.status(201).json(r.rows[0])}));
app.post('/api/disputes',requireAuth,asyncRoute(async(req,res)=>{const {orderId,reason,description}=req.body;const ok=await query("select id from orders where id=$1 and buyer_id=$2 and payment_status='paid'",[orderId,req.user.sub]);if(!ok.rowCount)return res.status(403).json({error:'Invalid order'});const r=await query('insert into disputes(order_id,opened_by,reason,description) values($1,$2,$3,$4) returning *',[orderId,req.user.sub,reason,description]);await query("update orders set escrow_status='disputed',status='disputed' where id=$1",[orderId]);res.status(201).json(r.rows[0])}));
app.get('/api/disputes',requireAuth,asyncRoute(async(req,res)=>res.json((req.user.role==='admin'?await query('select d.*,o.total,u.name opener from disputes d join orders o on o.id=d.order_id join users u on u.id=d.opened_by order by d.created_at desc'):await query('select d.*,o.total from disputes d join orders o on o.id=d.order_id where d.opened_by=$1 order by d.created_at desc',[req.user.sub])).rows)));
app.patch('/api/disputes/:id',requireAuth,requireRole('admin'),asyncRoute(async(req,res)=>{const {status,resolution}=req.body;const r=await query('update disputes set status=$1,resolution=$2,resolved_at=case when $1=\'resolved\' then now() else null end where id=$3 returning *',[status,resolution||null,req.params.id]);if(status==='resolved')await query("update orders set escrow_status='resolved' where id=(select order_id from disputes where id=$1)",[req.params.id]);res.json(r.rows[0])}));
app.get('/api/admin/sellers/pending',requireAuth,requireRole('admin'),asyncRoute(async(req,res)=>res.json((await query("select a.*,u.name,u.email from seller_applications a join users u on u.id=a.user_id where a.status='pending' order by a.created_at")).rows)));
app.patch('/api/admin/sellers/:id',requireAuth,requireRole('admin'),asyncRoute(async(req,res)=>{const a=(await query('select * from seller_applications where id=$1',[req.params.id])).rows[0];if(!a)return res.status(404).json({error:'Application not found'});if(req.body.status==='approved'){await query("update seller_applications set status='approved',reviewed_at=now() where id=$1",[a.id]);await query("update users set role='seller' where id=$1",[a.user_id]);return res.json((await query('insert into sellers(user_id,business_name,country) values($1,$2,$3) on conflict(user_id) do update set business_name=excluded.business_name returning *',[a.user_id,a.business_name,a.country])).rows[0])}await query("update seller_applications set status='rejected',reviewed_at=now() where id=$1",[a.id]);res.json({status:'rejected'})}));
app.post('/api/admin/broadcasts',requireAuth,requireRole('admin'),asyncRoute(async(req,res)=>{const {audience,subject,body}=req.body;let where='1=1';if(audience==='buyers')where="role='buyer'";if(audience==='sellers')where="role='seller'";const users=(await query(`select email,name from users where ${where}`)).rows;const b=(await query('insert into broadcasts(admin_id,audience,subject,body,recipient_count,status) values($1,$2,$3,$4,$5,$6) returning *',[req.user.sub,audience,subject,body,users.length,resend?'sending':'needs_email_provider'])).rows[0];if(resend){for(const u of users)await resend.emails.send({from:process.env.EMAIL_FROM,to:u.email,subject,html:`<div style="font-family:Arial"><h2>${subject}</h2><p>${String(body).replace(/\n/g,'<br>')}</p></div>`});await query("update broadcasts set status='sent' where id=$1",[b.id])}res.status(201).json(b)}));
app.get('/api/admin/stats',requireAuth,requireRole('admin'),asyncRoute(async(req,res)=>{const r=await query(`select (select count(*) from users) users,(select count(*) from sellers) sellers,(select count(*) from products where active) products,(select count(*) from orders) orders,(select coalesce(sum(total),0) from orders where payment_status='paid') gmv,(select count(*) from disputes where status!='resolved') open_disputes`);res.json(r.rows[0])}));
io.on('connection',socket=>socket.on('join_conversation',id=>socket.join(id)));
const FRONTEND_DIR=path.resolve(__dirname,'..');
app.use(express.static(FRONTEND_DIR,{index:'index.html'}));
app.get('*',(req,res,next)=>{
  res.sendFile('index.html',{root:FRONTEND_DIR},err=>{
    if(err){console.error('Frontend file error:',err);return next(err)}
  });
});
app.use((err,req,res,next)=>{
  console.error('Unhandled server error:',err);
  const status=Number(err.statusCode)||500;
  const safeMessage=(status>=500 && process.env.NODE_ENV==='production' && err.code!=='JWT_SECRET_MISSING')?'Internal server error':(err.message||'Request failed');
  res.status(status).json({error:safeMessage});
});
const PORT=Number(process.env.PORT||8080),HOST=process.env.HOST||'0.0.0.0'; server.listen(PORT,HOST,()=>console.log(`Dexillionz API listening on ${HOST}:${PORT}`));
